config/routes.rb
Honoluluanswers::Application.routes.draw do
  root :to => "home#index"

  # Content management
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :sessions => "sessions" }

  match '/about' => "home#about" , :as => :about
  match '/search/' => "search#index" , :as => :search, :via => [:get, :post]

  resources :categories, :only => :show

  # legacy, redirects to the appropriate specific resource
  resources :articles, :only => [:show, :article_type]

  resources :quick_answers, :only => :show
  resources :web_services, :only => :show
  resources :guides, :only => :show
  match '/articles/article-type/:content_type' => "articles#article_type"

  match "/admin/markdown-cheatsheet" => "admin/articles#download_markdown_cheatsheet", :as => "markdown_cheatsheet"
end

app/models/guide_step.rb
class GuideStep < ActiveRecord::Base
  belongs_to :guide, :class_name => 'Article', :foreign_key => 'article_id'
  attr_accessible :article_id, :title, :content, :preview, :step

  delegate :category, :tags, :keywords, :to => :guide

  after_save { guide.update_tank_indexes }
  after_destroy { guide.delete_tank_indexes }

  after_create do
    guide.create_analysis
  end

  after_update do
    guide.text_analyser.delay(:priority => 1).update_analysis
  end

  after_destroy do
    guide.destroy_analysis
  end

end

app/views/admin/guide_steps/_form.html.erb
<%= render :partial => 'shared/pagedown' %>


<h3 id="markdown-cheatsheet">
  <strong>Need help editing content?</strong> Read the
  <%= link_to("Markdown Cheatsheet (PDF)", markdown_cheatsheet_path, :id => "markdown-cheatsheet") %>
</h3>

<%= semantic_form_for [:admin, @guide_step] do |f| %>
  <%= f.inputs "Guide Steps Details" do %>
    <%=f.input :guide, :as => :select, :collection => Guide.all %>
    <%=f.input :title %>
    <%=f.input :step %>

    <div class="wmd-panel">
      <div id="wmd-button-bar-content" class="wmd-button-bar"></div>
      <%= f.input :content, :label => "Content", :input_html => {
          :class => 'wmd-input', :id => 'wmd-input-content'} %>
      <div id="wmd-preview-content" class="wmd-preview article"></div>
    </div>
    <div class="clear"></div>

  <%end%>
  <%=f.actions %>
<% end %>