config/routes.rb
Honoluluanswers::Application.routes.draw do
  root :to => "home#index"

  # Content management
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :sessions => "sessions" }

  match '/about' => "home#about" , :as => :about
  match '/search/' => "search#index" , :as => :search, :via => [:get, :post]

  resources :categories, :only => :show

  # legacy, redirects to the appropriate specific resource
  resources :articles, :only => [:show, :article_type]

  resources :quick_answers, :only => :show
  resources :web_services, :only => :show
  resources :guides, :only => :show
  match '/articles/article-type/:content_type' => "articles#article_type"

  match "/admin/markdown-cheatsheet" => "admin/articles#download_markdown_cheatsheet", :as => "markdown_cheatsheet"
end

app/views/shared/_articles_sidebar.html.erb
      <div class="sidebar">  
        <%= render(:partial => 'shared/flash_info') if flash[:info] %>
        <% unless @article.contact.nil? %>
          <div class="sidebar-unit">
            <h4 class="side-head">NEED MORE INFO?</h4>
            <div class="sidebar-content">
              <% if @article.contact.url.index(',') == nil %>
                <%= content_tag(:h4, link_to_unless(@article.contact.url.blank?, @article.contact.name, @article.contact.url, :target => "_blank")) %>
              <% elsif !(@article.contact.url.blank?) %>
                <%= content_tag(:h4, @article.contact.name) %>
                <% ( @article.contact.url.split(',') ).each do |multiurl| %>
                  <%= link_to(multiurl.strip, multiurl.strip) %>
                  <br/>
                <% end %>
                <br/>
              <% end %>
              <%= raw @article.contact.address %>
              <% if @article.contact.number.length > 0 %>
                <%= raw "Phone: #{@article.contact.number}" %>
              <% end %>
            </div>
          </div>
        <% end %>
        <% if @article.keywords.count > 0 %>
          <% unless @article.related.empty? %>
            <div class="sidebar-unit">
              <h4 class="side-head">RELATED TOPICS</h4>
              <div class="sidebar-content">
                <ul>
                  <% @article.related.each do |art| %>
                    <% if art.published? %>
                      <%= content_tag(:li, link_to(art.title, article_path(art.id)) ) %>
                    <% end %>
                  <% end -%>
                </ul>
              </div>
            </div>
          <% end -%>
        <% end -%>
        <% unless @article.author_name.blank? %>
          <div class="sidebar-unit">
            <h4 class="side-head">AUTHORED BY</h4>
            <div class="sidebar-content">
              <ul>
                <% if @article.author_link.blank? %>
                  <%= content_tag(:li, @article.author_name ) %>
                <% else %>
                  <%= content_tag(:li, link_to(@article.author_name, @article.author_link) ) %>
                <% end -%>
                <% if @article.author_pic? %>
                  <li><%= image_tag(@article.author_pic.url(:thumb) ) %></li>
                <% end -%>
              </ul>
            </div>
          </div>
        <% end -%>
      </div>

app/views/shared/_categories_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar-unit">
    <h4 class="side-head">ALL CATEGORIES</h4>
    <div class="sidebar-content">
       <ul>
        <% Category.order(:name).each do |c| %>
          <%= content_tag( :li, link_to(c.name, category_path(c.id))) %>
        <% end -%>
       </ul>
    </div>
  </div>
</div>

app/views/shared/_flash_info.html.erb
<div class="alert alert-info" >
  <%= flash[:info] %>
  <button href="#" class="close" onclick="$('div.sidebar div.alert').hide();">&times</a>
</div>

app/views/shared/_pagedown.html.erb
<%# encoding: utf-8 %>

<!-- Allows the partial to be used for all form partials -->
<% @article = @web_service || @quick_answer || @guide %>

<% @button_name = @article.class.to_s.split(/(?=[A-Z])/).join('_').downcase %>

<style type="text/css">
/* Removing outline border on active links (WCAG safe - active state links handled explicitly below) */
.article a:focus, .article a:active { 
  outline: 0;
  background-color: rgb(255,222,77);
  color: black;
}

.article .clearfix:after { content: "."; display: block; height: 0; clear: both; visibility: hidden; }
.article .clearfix { display: inline-block; }
* html .clearfix { height: 1%; }
.article .clearfix { display: block; }
.article {
 font: 100%/1.5 "Helvetica Neue", Helvetica, Tahoma, Arial, sans-serif;
}
.article h2, .article h3, .article h4, .article h5, .article h6 { font: 100%/1.5 "Helvetica Neue", Helvetica, Tahoma, Arial, sans-serif; line-height: 100%; }
.article h1 {
  font-family: "Archivo Narrow", "News Cycle", "Helvetica Neue", Helvetica, Tahoma, Arial, sans-serif; line-height: 100%;
  font-size: 30px; 
}
.article h2 {
  font-size: 18px;
}
.article h3.content-type {
  padding: 10px 15px;
  color: #FFF;
  background-color: #000;
  display: inline-block;
  text-transform: uppercase;
  margin-left: -30px;
  margin-bottom: 15px;
  font-family: Oswald, "News Cycle", Helvetica, Tahoma, Arial, sans-serif;
  font-size: 14px;
  letter-spacing: 0.07em;
}
.article p {
  /*font-size: 1.1em;*/
  color: #070707;
  font-weight: 300;
  margin: 10px 0;
}
.article p.preview {
  font-weight: 300;
  margin-bottom: 0px;
}

.article p a, .article h1 a, .article h2 a, .article h3 a, .article h4 a, .article li a{
  color: rgb(0,136,204);
  border-bottom: none;
}

.article p a:hover{
  color: rgb(0,136,204);
  border-bottom: 1px solid #ffde4d;
}

.article table a{
  border-bottom: none;
}

.article a { 
  border-bottom: 1px solid #ffde4d;
}

.article a:hover{
  border-bottom: 1px solid #ffde4d;
  text-decoration: none;
  color: rgb(0,136,204);
}
.article p.call {
  font-size: 20px; 
  margin-bottom: 20px;
  text-align: center;
}
.article .pop-heading h2 {
  font-size:20px;
  font-weight: bold;
  margin-bottom: 10px;
}
.article div.content-text {
  padding-top: 20px;
  font-weight: 300;
}
.article .content-text h2 {
  margin-bottom: 20px;
  font-weight: bold;
  line-height: 150%;
}
.article .content-text h3 {
  margin-top: 40px;
  text-transform: uppercase;
  font-weight: bold;

}
.article .content-text p {
  color: rgb(51, 51, 51);
  margin-bottom: 12px;
}
.article .content-text ol, .content-text ul {
  margin: 0 12px;
  padding: 0 10px;
}
.article .content-text ol li, .content-text ul li{
  margin: 0 0 12px 30px;
  padding-left: 5px;
} 
.article ul li {
  list-style-type: disc;
}
.article ol li {  
  list-style-type: decimal;
}
.article ul ol > li {  
  list-style-type: decimal;
}
.article ol ul > li {
  list-style-type: disc;
}
.article div.quick_top{
  background: whitesmoke;
  padding: 20px;
}

/* TABLE */
.article table, .article th, .article td {
  padding: 5px;
}
.article table {
  width: 80%;
  margin: auto;
}
.article th {
  text-align: left;
  background-color: #f8f8f8;
}
.article td {
  text-align: left;
  background-color: #ededed;
  margin: 1px;
}

/*accessibility*/
.article a:focus, .article a:active { 
  color: black;
}

.article .highlight {
	font-weight:bold;
}

.article > ol li, .article > ul li{
    margin: 2px 44px;
}

.article blockquote{
  font-style: normal;
}

.article th{
  background-color: #f8f8f8;
}

#wmd-preview-content em strong {
  padding: 10px;
  background-color: #D5E8F3;
  line-height: 30px;
  font-weight: normal;
  font-style: normal;
  margin-right: 20px;
  margin-left: 20px;
  margin-top: 14px;
  display: block;
  margin-bottom: 14px;
}

#wmd-preview-content strong em {
  padding: 10px;
  background-color: #D5E8F3;
  line-height: 30px;
  font-weight: normal;
  font-style: normal;
  margin-right: 20px;
  margin-left: 20px;
  margin-top: 14px;
  display: block;
  margin-bottom: 14px;
}

.commit{
  display: inline;
  margin: 12px;
  list-style-type: none;
}

form input[type="button"] {
  background: #838A90;
  background: -webkit-gradient(linear, left top, left bottom, from(#838A90), to(#414549));
  background: -moz-linear-gradient(-90deg, #838A90, #414549);
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#838a90, endColorstr=#414549);
  -ms-filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#838a90, endColorstr=#414549);
  -webkit-border-radius: 200px;
  -moz-border-radius: 200px;
  border-radius: 200px;
  text-shadow: #000 0 1px 0;
  -webkit-box-shadow: 0 1px 0px rgba(0, 0, 0, 0.1),0 0 0 1px rgba(255, 255, 255, 0.2) inset;
  box-shadow: 0 1px 0px rgba(0, 0, 0, 0.1),0 0 0 1px rgba(255, 255, 255, 0.2) inset;
  border: solid 1px #484E53;
  border-color: #484E53;
  border-top-color: #616A71;
  border-right-color: #484E53;
  border-bottom-color: #363B3F;
  border-left-color: #484E53;
  color: #EFEFEF;
  display: inline-block;
  font-weight: bold;
  font-size: 1.0em;
  font-family: Helvetica, Arial, sans-serif;
  line-height: 12px;
  margin-right: 3px;
  padding: 7px 16px 6px;
  text-decoration: none;
  -webkit-font-smoothing: antialiased;
  cursor: pointer;
  *display: inline;
  _display: inline;
}

</style>

<script type="text/javascript">
$(document).ready(function() {

  // instantiate pagedown 
  var converter_content              = new Markdown.getSanitizingConverter();
  var converter_content_main         = new Markdown.getSanitizingConverter();
  var converter_content_main_extra   = new Markdown.getSanitizingConverter();
  var converter_content_need_to_know = new Markdown.getSanitizingConverter();

  Markdown.Extra.init(converter_content,              {extensions: "all"});
  Markdown.Extra.init(converter_content_main,         {extensions: "all"});
  Markdown.Extra.init(converter_content_main_extra,   {extensions: "all"});
  Markdown.Extra.init(converter_content_need_to_know, {extensions: "all"});

  try{
    var editor_content_main = new Markdown.Editor(
      converter_content_main, "-content_main");
      editor_content_main.run();    
  }
  catch(e){}

  try{
    var editor_content_main_extra = new Markdown.Editor(
      converter_content_main_extra, "-content_main_extra");
      editor_content_main_extra.run();
  }
  catch(e){}

  try{    
    var editor_content_need_to_know = new Markdown.Editor(
      converter_content_need_to_know, "-content_need_to_know");
      editor_content_need_to_know.run();
  }
  catch(e){}

  try{
    var editor_content = new Markdown.Editor(
      converter_content, "-content");
      editor_content.run();
  }
  catch(e){}

});
</script>

app/views/shared/_search_form.html.erb
  <%= form_tag('/search', :id => 'search', :class => 'right', :style => 'text-align:right;', :method => 'get') do %>
    <%= text_field_tag :q, nil, :id => 'query', :class => 'x-large', :size => 20, :width => '160', :placeholder => 'Search...', :style => 'width:50%;padding-left:6px;' %>
    <%= submit_tag 'Search', :class => 'btn-search', :name => nil, :id => 'query-btn' %>
  <% end %>

app/views/shared/_twitter_share.html.erb
<div id="twitter_share">
  <a href="https://twitter.com/share" class="twitter-share-button" data-text="- @HonoluluAnswers" data-count="none" data-related="HonoluluAnswers" data-hashtags="">Tweet</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></script>
</div>